databases:
  - name: plantillar
    databaseName: plantillar
    user: plantillar
    plan: free

services:
  - type: web
    name: plantillar
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    # preDeployCommand: "bundle exec rails db:migrate" # preDeployCommand only available on paid instance types
    startCommand: "bundle exec rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: plantillar
          property: connectionString
      - key: 324bbc485329fd01395de2f94caa9e7e
        sync: false
      - key: WEB_CONCURRENCY
        value: 2 # sensible default